# Generated by Django 5.2 on 2025-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_remove_usuario_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
