# Generated by Django 5.2 on 2025-07-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_usuario_dni_usuario_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hours', models.PositiveIntegerField()),
                ('program_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='system.trainingprogram'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
