# Generated by Django 5.2 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_trainingprogram_remove_certificate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='modality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
