# Generated by Django 5.2 on 2025-08-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_certificate_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
